name: flutter_widgets
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bs_flutter: ^0.4.7
  fluttertoast: ^8.0.9
  flutter_screenutil: ^5.5.3+2
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic