name: firebase_login_logout
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
   - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
